language: minimal

git:
  depth: 1

services:
  - docker

before_install:
  - source <(curl 'https://raw.githubusercontent.com/madworx/cd-ci-glue/master/src/cd-ci-glue.bash')

before_script:
  - make docker-build

script:
  - make tests

after_success:
  - make docker-label-versions
  - docker tag $(make get-image-name):latest $(make get-image-name):$(date +%Y%m)
  - dockerhub_push_image $(make get-image-name):latest
  - dockerhub_push_image $(make get-image-name):$(date +%Y%m)
  