language: python

python: 
  - "3.6"

git:
  depth: 1

services:
  - docker

before_install:
  - source <(curl 'https://raw.githubusercontent.com/madworx/cd-ci-glue/master/src/cd-ci-glue.bash')

before_script:
  - make docker-build

script:
  - make tests
  - make docker-label-versions
  - make release
